version: '3.8'

services:

  mysql:
    build:
      context: ./mysql
    container_name: mysql
    restart: unless-stopped
    volumes:
      - mysql-db:/var/lib/mysql
    ports:
      - '3306:3306'

  phpmyadmin:
    build:
      context: ./mysql/phpmyadmn
    container_name: phpmyadmin
    ports:
      - "8082:80" 

  # ----------------------------------------------
  postgresql:
    build:
      context: ./postgres
    container_name: postgresql
    restart: always
    ports:
      - "5432:5432"

  pgadmin:
    build:
      context: ./postgres/pgadmin
    container_name: pgadmin4
    restart: always
    ports:
      - "8888:80"    

  #----------------------------------------------       
  mongodb:
    build:
      context: ./mongodb
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017" 

  #----------------------------------------------    
  cassandra:
    build:
      context: ./cassandra
    container_name: cassandra
    ports:
      - "9042:9042"
    volumes:
      - ~/apps/cassandra:/var/lib/cassandra    

volumes:
  mysql-db:
  postgresql:
  phpmyadmin:
  pgadmin:
