version: '3'

services:
  redis:
    image: "redis:latest"
    container_name: redis_container
    ports:
      - "6379:6379"
    restart: always
    networks:
      - my_network
    volumes:
      - redis-data:/data

  pgadmin4:
    image: "dpage/pgadmin4:latest"
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - my_network

volumes:
  redis-data:
  pgadmin-data:

networks:
  my_network:
