# Use the official pgAdmin 4 image as the base image
FROM dpage/pgadmin4:latest

# Set environment variables for pgAdmin 4
ENV PGADMIN_DEFAULT_EMAIL=user-name@domain-name.com
ENV PGADMIN_DEFAULT_PASSWORD=strong-password

