# Use the official PostgreSQL image as the base image
FROM postgres:latest

# Set environment variables for PostgreSQL
ENV POSTGRES_USER=user-name
ENV POSTGRES_PASSWORD=strong-password
ENV POSTGRES_DB=postgres

